media:
  input: public
  output: /
  extensions: [png, jpg, jpeg, gif, webp, svg, ico]

content:
  - name: posts
    label: Blog Posts
    type: collection
    path: src/content/blog
    icon: file-text
    fields:
      - name: title
        label: Title
        type: string
        required: true
      
      - name: description
        label: Description
        type: text
        required: true
      
      - name: pubDate
        label: Publication Date
        type: date
        required: true
        options:
          format: yyyy-MM-dd
      
      - name: updatedDate
        label: Last Updated
        type: date
        options:
          format: yyyy-MM-dd
      
      - name: heroImage
        label: Hero Image
        type: image
        options:
          path: public
          extensions: [png, jpg, jpeg, gif, webp, svg]
      
      - name: body
        label: Content
        type: rich-text
        options:
          format: markdown
          image:
            path: public
            extensions: [png, jpg, jpeg, gif, webp, svg]

    view:
      fields: [title, pubDate, updatedDate]
      primary: title
      sort: [pubDate, title]
      default:
        sort: pubDate
        order: desc
